"""initial

Revision ID: bb9836bf41bd
Revises: 
Create Date: 2025-04-09 23:03:01.993242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9836bf41bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS meta")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spider_file',
    sa.Column('storage_object_id', sa.UUID(), nullable=False, comment='filestorage.storage_object.id'),
    sa.Column('storage_object_name', sa.TEXT(), nullable=True, comment='filestorage.storage_object.name'),
    sa.Column('storage_object_site_id', sa.TEXT(), nullable=True, comment='filestorage.storage_object.site_id'),
    sa.Column('storage_version_size', sa.TEXT(), nullable=True, comment='filestorage.storage_version.size'),
    sa.Column('storage_version_link', sa.TEXT(), nullable=True, comment='filestorage.storage_version.link'),
    sa.Column('create_ts', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('target_path', sa.VARCHAR(length=1024), nullable=True, comment='file path'),
    sa.Column('status_id', sa.SMALLINT(), nullable=True, comment='0 - new, 1 - progress, 2 - done, 3 - error'),
    sa.PrimaryKeyConstraint('storage_object_id'),
    schema='meta'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spider_file', schema='meta')
    # ### end Alembic commands ###
